name: Generate sitemap for uni-cot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap.xml
        id: sm
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: projects/uni-cot
          base-url-path: https://sais-fuxi.github.io/projects/uni-cot/

      - name: Summary
        run: |
          echo "Sitemap: ${{ steps.sm.outputs.sitemap-path }}"
          echo "URLs:    ${{ steps.sm.outputs['url-count'] }}"
          echo "Excluded: ${{ steps.sm.outputs['excluded-count'] }}"

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "${{ steps.sm.outputs.sitemap-path }}"
            git commit -m "chore: update sitemap"
            git push
          else
            echo "No changes to commit."
          fi
